import { Developer } from "./developer.model";

export const developers: Developer[] = [
  {
    id: "1a2b3",
    firstName: "Fatima",
    lastName: "Jamal",
    level: "senior",
    type: "fullstack",
    country: "788",
    technos: ["Java", "Angular", "Azure", "MySQL"],
  },
  {
    id: "eb9ad",
    firstName: "Safa",
    lastName: "Hamderik",
    level: "expert",
    type: "frontend",
    country: "504",
    technos: ["React", "JavaScript"],
  },
  {
    id: "eae72",
    firstName: "Elodie",
    lastName: "Lawson",
    level: "expert",
    type: "backend",
    country: "768",
    technos: ["Node.Js", "PHP", "Reddis", "Nginx"],
  },
  {
    id: "6af17",
    firstName: "Anna",
    lastName: "Vales",
    level: "mid",
    type: "frontend",
    country: "380",
    technos: ["React", "JavaScript"],
  },
  {
    id: "72f39",
    firstName: "Tin",
    lastName: "Yang",
    level: "junior",
    type: "frontend",
    country: "250",
    technos: ["Angular", "JavaScript", "Java", "AWS"],
  },
  {
    id: "9bce3",
    firstName: "Albano",
    lastName: "Hugo",
    level: "senior",
    type: "frontend",
    country: "250",
    technos: ["Angular", "JavaScript"],
  },
  {
    id: "0b8b3",
    firstName: "Carlos",
    lastName: "Bianna",
    level: "mid",
    type: "frontend",
    country: "124",
    technos: ["Angular", "JavaScript"],
  },
  {
    id: "a267b",
    firstName: "Doris",
    lastName: "Emah",
    level: "expert",
    type: "fullstack",
    country: "380",
    technos: ["Angular", "JavaScript", "Java", "AWS", "MongoDB", "MySQL"],
  },
  {
    id: "03a42",
    firstName: "Kwaku",
    lastName: "Amah",
    level: "expert",
    type: "fullstack",
    country: "288",
    technos: ["Angular", "JavaScript", "Node.Js", "Heroku", "AWS", "MongoDB"],
  },
  {
    id: "2c0eb",
    firstName: "Vincent",
    lastName: "Lecoq",
    level: "junior",
    type: "backend",
    country: "250",
    technos: ["React", "C-Sharp", "MySQL", "MongoDb"],
  },
  {
    id: "c09f3",
    firstName: "Gill",
    lastName: "Alfredo",
    level: "mid",
    type: "fullstack",
    country: "768",
    technos: ["Vue", "PHP", "Node.Js", "MongoDB", "ExpressJs"],
  },
  {
    id: "ceb23",
    firstName: "Corrine",
    lastName: "Logan",
    level: "senior",
    type: "frontend",
    country: "392",
    technos: ["Angular", "JavaScript", "RxJS", "Vue", "Redux", "NgRx"],
  },
  {
    id: "8c5a2",
    firstName: "Florian",
    lastName: "Stéphan",
    level: "mid",
    type: "frontend",
    country: "250",
    technos: ["Svlete", "JavaScript", "React"],
  },
  {
    id: "03c4e",
    firstName: "GanGah",
    lastName: "Amedi",
    level: "expert",
    type: "backend",
    country: "768",
    technos: ["C-Sharp", "Java", "AWS", "Terraform"],
  },
  {
    id: "15c2e",
    firstName: "Amadou",
    lastName: "Moustapha",
    level: "mid",
    type: "backend",
    country: "756",
    technos: ["PHP", "Java", "Reddis", "MariaDb"],
  },
  {
    id: "a2c3b",
    firstName: "Geordy",
    lastName: "Assem",
    level: "expert",
    type: "fullstack",
    country: "266",
    technos: ["Vue", "PHP", "Azure", "AWS"],
  },
  {
    id: "a5bec",
    firstName: "Laura",
    lastName: "Bill",
    level: "junior",
    type: "fullstack",
    country: "392",
    technos: ["Angular", "JavaScript", "Node.Js", "MongoDB", "ExpressJs"],
  },
  {
    id: "e5b8d",
    firstName: "Djoh",
    lastName: "Debgi",
    level: "expert",
    type: "frontend",
    country: "120",
    technos: ["Angular", "JavaScript"],
  },
  {
    id: "9ecb1",
    firstName: "Eva",
    lastName: "Zanah",
    level: "mid",
    type: "fullstack",
    country: "124",
    technos: ["Angular", "JavaScript", "Java", "Nginx", "MongoDb"],
  },
];
